Fix multiple tab selection via `data-vc-tabs`.
w3c/respec-vc pull request #29
Opened 2024-06-10 15:52 UTC by BigBlueHat

2024-06-10 19:36 UTC, TallTed requested changes

2024-06-10 19:36 UTC, TallTed commented on CHANGELOG.md
> +- Fixed `data-vc-tabs` to work with multiple space delimited values.
```suggestion
- Fixed `data-vc-tabs` to work with multiple space-delimited values.
```

2024-06-10 19:36 UTC, TallTed commented on README.md
> +The `data-vc-tabs` property can be set to a space delimited list containing any
```suggestion
The `data-vc-tabs` property can be set to a space-delimited list containing any
```

2024-06-11 13:16 UTC, iherman approved these changes

2024-06-18 12:49 UTC, msporny approved these changes

2024-06-18 13:01 UTC, merged