Support rendering Enveloped Verifiable Presentations
w3c/respec-vc pull request #40
Opened 2024-08-06 01:42 UTC by decentralgabe

fix #39

2024-08-06 01:52 UTC, selfissued approved these changes

2024-08-06 14:43 UTC, TallTed requested changes

2024-08-06 14:43 UTC, TallTed commented on index.html
> +  <pre class="example nohighlight vc" data-vc-tabs="jose sd-jwt cose" title="An EnvelopedVerifiableCredential Verifiable Presentation example">
```suggestion
  <pre class="example nohighlight vc" data-vc-tabs="jose sd-jwt cose" title="An example  Verifiable Presentation with an EnvelopedVerifiableCredential">
```

2024-08-06 14:43 UTC, TallTed commented on index.html
> +  <pre class="example nohighlight vc" data-vc-tabs="jose sd-jwt cose" title="An EnvelopedVerifiablePresentation Verifiable Presentation example">
```suggestion
  <pre class="example nohighlight vc" data-vc-tabs="jose sd-jwt cose" title="An example  Verifiable Presentation with an EnvelopedVerifiablePresentation">
```

2024-08-07 15:06 UTC, merged

2024-08-07 15:06 UTC, decentralgabe commented
@msporny will need your help creating a release, when you get a chance, please.

2024-08-07 15:29 UTC, decentralgabe commented
so https://cdn.jsdelivr.net/gh/w3c/respec-vc@3.3.2/dist/main.js exists
but https://cdn.jsdelivr.net/gh/w3c/respec-vc@3.3.3/dist/main.js does not

I am not sure how you got the `dist` folder and artifacts to be present for 3.3.2...

2024-08-07 16:10 UTC, msporny commented
You have to build and check in the dist folder but ONLY on the tag (it becomes a disconnected branch commit). 

If that doesn't make sense, we'll push your changes out when we fix the Echidna stuff. Let me check w/ @BigBlueHat if those changes are ready to go and I'll try to push a release out.

You /might/ be able to update the `3.3.3` tag w/ the `dist/main.js` checked in, but I have no idea if jsdelivr caches tag releases temporarily/permanently, or checks for hash changes? We might have to mark `3.3.3` as a broken tag release?

2024-08-08 01:37 UTC, decentralgabe commented
thanks @msporny that worked -- https://cdn.jsdelivr.net/gh/w3c/respec-vc@3.3.3/dist/main.js